### ISSUE TITLE
Error running build.cmd

### ISSUE THREAD

**Issue by matkuki** [mmozeiko/build-sdl2#1]
Hi,

Running `build.com`, the build stops at:
![image](https://user-images.githubusercontent.com/10289651/197253863-604abcbb-1e43-4006-a1d1-6c3aeb80de98.png)
How can this be fixed?

**Comment by mmozeiko** [comment]
This probably means that your path or cmake setup has glut library available somewhere. And tiff configures itself to use it, but then somehow cannot find headers for it.

You can check `CMakeFiles/CMakeError.log` or `CMakeCache.txt` files in tiff-4.4.0 folder for more details to see where it finds the glut header/library. And then remove it.

Unfortunately current libtiff 4.4.0 version does allow to configure build to not build the tools, so if you don't want to fix path/cmake setup, then you'll need to patch tiff CMakeLists.txt file. Next version will be able to disable tools building that can prevent this kind of error.

**Comment by matkuki** [comment]
Ok, thanks.
